#0-SetupProject#
================
This file is to create a new project for the simple HIV model.
The example used is project investigating the impact of COVID-19 (COVID-19impact).

```{r Initialise}
# Only requires base R

# Core folders
dataFolder <- file.path(getwd(), "data")
projects <- file.path(getwd(), "projects")

```



Copy all needed files for the model.
```{r Create project}

name <- "COVID-19impact"

# If project not already created make sure it is not overwritten
if (!file.exists(file.path(projects, name, "project_specs.csv"))) {
    # Create project folders 
    dir.create(file.path(projects, name))
    dir.create(file.path(projects, name,"output"))
    dir.create(file.path(projects, name, "figures"))
    
    # Create blank input files by copying the template files
    #project_specs <- data.frame(spec = c("name", "statyear", "steps", "stepsize", "betaoption"), value = rep(0,5))
    
    #write csv in the template file
    #write.csv(project_specs, file = file.path(dataFolder, "templates", "project_specs.csv"))
    
    file.copy(file.path(dataFolder, "templates", "project_specs.csv"), file.path(projects, name))
    file.copy(file.path(dataFolder, "templates", "hiv_default_para.csv"), file.path(projects, name))
    file.copy(file.path(dataFolder, "templates", "hiv_fixed_data.csv"), file.path(projects, name))
    file.copy(file.path(dataFolder, "templates", "hiv_time_series_data.csv"), file.path(projects, name))
}

```

