# 1_input and run model.Rmd#

#This script is to input all the data and run the SIMPLE HIV model for a specified
project.

```{r Initialise}
##setwd()

#######################r initialization####################
# Clear workspace
rm(list=ls()) 

# Source to current directory and set working directory
basePath <- getwd()
library(dplyr)
# Restart R and set working directory to source file location. 

##r User inputs
##select project
selectedproject<- "COVID-19impact"

# Various directories
projectFolder <- file.path(basePath,"projects", selectedproject)
dataFolder <- file.path(basePath,"projects", selectedproject,"data")
resultsFolder <- file.path(basePath,"projects", selectedproject, "output")
figFolder <- file.path(basePath,"projects", selectedproject,"figures")
Rcode <- file.path(basePath, "code") 

# Load standard libraries, key functions and options
# source(file.path(Rcode, "LoadLibrary.R"))
# source(file.path(Rcode, "DataLibraries.R"))
source(file.path(Rcode, "SimpleHiv.R"))
source(file.path(Rcode, "BetaOption.R"))
source(file.path(Rcode, "Parameters.R"))

```


```{r Input}
# Specify project input files and load them
hivfixeddataFile<- file.path(dataFolder,  "hiv_fixed_data.csv")
hivFixeddata<-read.csv(hivfixeddataFile,fileEncoding = 'UTF-8-BOM')

hivtimeseriesFile<- file.path(dataFolder,  "hiv_time_series_data.csv")
hivTimeseries<-read.csv(hivtimeseriesFile,fileEncoding = 'UTF-8-BOM')

specificationsFile<- file.path(dataFolder,  "project_specs.csv")
projectSpecs<-read.csv(specificationsFile,fileEncoding = 'UTF-8-BOM')

##Scenarios file##
prepScenario3File<- file.path(dataFolder,  "prep_estimate_predicted_use.csv")
prepScenario3<-read.csv(prepScenario3File,fileEncoding = 'UTF-8-BOM')
condomScenario3File<- file.path(dataFolder,  "condom_estimate_predicted_use.csv")
condomScenario3<-read.csv(condomScenario3File,fileEncoding = 'UTF-8-BOM')


# From project files extract key project parameters ----------------------------

times<- as.numeric(projectSpecs$steps) 
startyear<- as.numeric(projectSpecs$startyear) 
projectParams <- Parameters(hivFixeddata, hivTimeseries, projectSpecs) #Default params in the project

adjustedPara <- projectParams
# Set-up initial conditions - same for all scenarios
initial_state_values<-as.list(c(N=hivFixeddata$value[hivFixeddata$Para == "plhiv"],                                            
                              I=hivFixeddata$value[hivFixeddata$Para == "newinf"],#new infections
                              d=hivFixeddata$value[hivFixeddata$Para == "prodiag"]))#proportion diagnosed

##############debugonce(SimpleHIV)
```

```{r Set-up scenarios}

#Script for reading scenario parameters returning a list of parameter sets
#load scenarios
source(file.path(projectFolder, "GenerateScenarios.R"))
scenarios <- GenerateScenarios(adjustedPara)
projectSpecs$nscenarios <- length(scenarios)


```



```{r running model}
#all results in one dataset
infectionresults<-data.frame( 
                       timestep = integer(),
                       scenarios = character(),
                       newHIV = numeric(),
                       totalHIV = numeric(),
                       percentage_diagnosis = numeric(),
                       diagnosis = numeric())
###diagnosis<-list()
for (ii in 1:projectSpecs$nscenarios) {
  output<- SimpleHIV(times=times, 
                     state = initial_state_values,
                     parameters = scenarios[[ii]])
  infectionresults<-rbind(infectionresults,data.frame( 
                       timestep = c(0:(times-1)),
                       scenarios = ii,
                       newHIV = output$I,
                       totalHIV = output$N[1:times],
                       percentage_diagnosis = output$d[1:times],
                       diagnosis = output$diagnosis[1:times]))
}

ylabels <- c()
for (ii in 1:projectSpecs$nscenarios) {
    ylabels[ii] <- scenarios[[ii]]$label
}

infectionresults$scenarios<-factor(infectionresults$scenarios,levels =  
                                      c(1:projectSpecs$nscenarios),labels = ylabels)

###add a column of cumulated number of new infections and a column of cumulated number of diagnosis
#mutate(group_by(newinfectionresults,scenarios), csum=cumsum(newHIV))
infectionresults<- infectionresults %>% 
  mutate(infection1 = ifelse(timestep==0,0,newHIV)) %>% group_by(scenarios) %>% mutate(csum_infection = cumsum(infection1))
infectionresults<- infectionresults %>% 
  mutate(diagnosis1 = ifelse(timestep==0,0,diagnosis))%>% group_by(scenarios) %>% mutate(csum_diagnosis = cumsum(diagnosis1))

###add a colum of the variable "year"###
infectionresults$year<-c(2019,rep(2020,12),rep(2021,12),rep(2022,8),2019,rep(2020,12),rep(2021,12),rep(2022,8),2019,rep(2020,12),rep(2021,12),rep(2022,8))
#infectionresults$year<-rep(c(rep(projectSpecs$startyear,1),rep(projectSpecs$startyear+1,12),rep(projectSpecs$startyear+2,12),rep(projectSpecs$startyear+3,8)),projectSpecs$nscenarios)

#add a column of cumulated number of new infections and a column of cumulated number of diagnosis
infectionresults <- infectionresults %>%
group_by(scenarios,year) %>%
  mutate(csum_year_infection=cumsum(newHIV))
infectionresults <- infectionresults %>%
group_by(scenarios,year) %>%
  mutate(csum_year_diagnosis=cumsum(diagnosis))

#Generate the number of new infections per year in different scenarios
newinfections_peryear <- infectionresults %>%
group_by(scenarios,year) %>%
  summarise(Sum=round(sum(newHIV),0))
diagnosis_peryear <- infectionresults %>%
group_by(scenarios,year) %>%
  summarise(Sum=round(sum(diagnosis),0))


#Save output in some form Rda file and/or csv
# If file not already created make sure it is not overwritten
if (!file.exists(file.path(resultsFolder, "infectionresults_1020.csv"))) {
write.csv(infectionresults, file = file.path(resultsFolder, "infectionresults_1020.csv"))
}

```



```{r simulation}
numsims <- 1000 # number of sampled parameter sets to run
  # Generate and store a random integer for set.seed so we can rerun 
  # things exactly if we want to
  currseed <- 113210 #sample(1:10^6, 1) #113210
  set.seed(currseed)
  
 paramsSets <- list()
 params2sampleOnce <- c("plhiv", "newinf", "prodiag", "proART", "prosupp", "PrEPcov", "conduse", "sexact", "testpro", "effisupp", "effiPrEP", "efficon")
    params2sampletwice <- c("acts","condoms","testing","prep","immigrants","emigrants","Deaths","tau","sigma") 
    
        #paramsSets[["year"]] <- rep(years, numsims)
    
    # Fixed parameters
    for (var in params2sampleOnce) {
      # Sample from parameter range and duplicate across years
      temp <- runif(numsims,( hivFixeddata %>% filter(Para == var))$lower, 
        (hivFixeddata %>% filter(Para == var))$upper) 
  
      
      paramsSets[[var]] <- temp
    }
  
  #paramsSets

temporal_data<-  as.data.frame(cbind(acts=c(hivTimeseries$acts),
                                     condoms=c(hivTimeseries$condoms), 
                                     testing= c(hivTimeseries$testing),
                                     prep=c(hivTimeseries$prep),
                                     immigrants=c(hivTimeseries$immigrants),
                                     emigrants=c(hivTimeseries$emigrants),
                                     Deaths=c(hivTimeseries$Deaths),
                                     tau=c(hivTimeseries$tau),
                                     sigma=c(hivTimeseries$sigma)))

temporal_data<-as.list(temporal_data)

# Time varying parameters - sampled from multiplicative factor range at each 
    # end and then connect linearly to change the best estimate values.  
    for (var in params2sampletwice) {
      
      tempStart <-  runif(numsims,(hivFixeddata %>% 
          filter(Para == paste0(var, "_range")))$lower, 
        (hivFixeddata %>% filter(Para == paste0(var,"_range")))$upper)
      tempEnd <- runif(numsims,(hivFixeddata %>% 
          filter(Para == paste0(var, "_range")))$lower, 
        (hivFixeddata %>% filter(Para == paste0(var, "_range")))$upper)
      
      # Update best estimate using sampled multiplicative factors for each sim
      varVector <- vector()
      for (ii in 1:numsims) {
        
        varVector <- c(varVector, seq(tempStart[ii], tempEnd[ii], length = times)*
        temporal_data[[var]])
        
        paramsSets[[var]] <- varVector
        
      }
      varVector_base <- vector()
      for (ii in 1:numsims) {
        
        varVector_base <- c(varVector_base, seq(tempStart[ii], tempEnd[ii], length = times))
        paramsSets[[paste0(var, "_base")]] <- varVector_base
        
      }
    }

paramsSets$condoms_scenario3<-paramsSets$condoms_base*condomScenario3$relativenumber
paramsSets$prep_scenario3<- paramsSets$prep_base*prepScenario3$relativenumber
#paramsSets
infectionresults_sim<-data.frame( 
                       timestep = integer(),
                       scenarios = character(),
                       numsim = integer(),
                       newHIV = numeric(),
                       totalHIV = numeric(),
                       percentage_diagnosis = numeric(),
                       diagnosis = numeric())

parasets_lists_COVID      <- vector("list", numsims)
output_sim_COVID          <- vector("list", numsims)
initial_state_values_sim_COVID <- vector("list", numsims)


 for (ii in 1:numsims) {
parasets_lists_COVID[[ii]]<- c(N0= paramsSets$plhiv[ii], 
               I0=paramsSets$newinf[ii], 
               d0=paramsSets$prodiag[ii], 
               tau0=paramsSets$tau[((ii-1)*times+1)], 
               sigma0=paramsSets$sigma[((ii-1)*times+1)],
               phi=paramsSets$effisupp[ii],  
               omega0= paramsSets$prep[((ii-1)*times+1)]*projectParams$omega0, 
               epsilon_PrEP=paramsSets$effiPrEP[ii],  
               epsilon_condom=paramsSets$efficon[ii],   
               chi_0=paramsSets$condoms[((ii-1)*times+1)]*projectParams$chi_0, 
               alpha0=paramsSets$acts[((ii-1)*times+1)]*projectParams$alpha0,  
               T= paramsSets$testing[((ii-1)*times+1)]*projectParams$T)
parasets_lists_COVID[[ii]]$beta0 <- betaoption1(parameters = parasets_lists_COVID[[ii]])
parasets_lists_COVID[[ii]]$alpha_t=c(paramsSets$acts[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$chi_t= c(paramsSets$condoms[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$T_p= c(paramsSets$testing[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$omega_p= c(paramsSets$prep[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$IM= c(paramsSets$immigrants[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$EM= c(paramsSets$emigrants[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$Death= c(paramsSets$Deaths[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$tau= c(paramsSets$tau[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_COVID[[ii]]$sigma= c(paramsSets$sigma[((ii-1)*times+1):((ii-1)*times+times)])

initial_state_values_sim_COVID[[ii]]<-as.list(c(N=parasets_lists_COVID[[ii]]$N0,  
                                    I=parasets_lists_COVID[[ii]]$I0,
                                    d=parasets_lists_COVID[[ii]]$d0))
output_sim_COVID[[ii]]<- SimpleHIV(times=times, 
                     state = initial_state_values_sim_COVID[[ii]],
                     parameters = parasets_lists_COVID[[ii]])

infectionresults_sim<-rbind(infectionresults_sim,data.frame( 
                       timestep = c(0:(times-1)),
                       scenarios = "With COVID-19 impact",
                       numsim = ii,
                       newHIV = output_sim_COVID[[ii]]$I, 
                       totalHIV = output_sim_COVID[[ii]]$N[1:times],
                       percentage_diagnosis = output_sim_COVID[[ii]]$d[1:times],
                       diagnosis = output_sim_COVID[[ii]]$diagnosis[1:times]))

 }

##scenaior without COVID-19 and remain##
output_sim_base <- vector("list", numsims)
parasets_lists_base <- vector("list", numsims)
initial_state_values_sim_base<- vector("list", numsims)

for (ii in 1:numsims) {
parasets_lists_base[[ii]]<- c(N0= paramsSets$plhiv[ii], 
               I0=paramsSets$newinf[ii], 
               d0=paramsSets$prodiag[ii], 
               tau0=paramsSets$tau_base[((ii-1)*times+1)]*projectParams$tau0, 
               sigma0=paramsSets$sigma_base[((ii-1)*times+1)]*projectParams$sigma0,
               phi=paramsSets$effisupp[ii],  
               omega0= paramsSets$prep_base[((ii-1)*times+1)]*projectParams$omega0, 
               epsilon_PrEP=paramsSets$effiPrEP[ii],  
               epsilon_condom=paramsSets$efficon[ii],   
               chi_0=paramsSets$condoms_base[((ii-1)*times+1)]*projectParams$chi_0, 
               alpha0=paramsSets$acts_base[((ii-1)*times+1)]*projectParams$alpha0,  
               T= paramsSets$testing_base[((ii-1)*times+1)]*projectParams$T)
parasets_lists_base[[ii]]$beta0 <- betaoption1(parameters = parasets_lists_base[[ii]])
parasets_lists_base[[ii]]$alpha_t=c(paramsSets$acts_base[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_base[[ii]]$chi_t= c(paramsSets$condoms_base[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_base[[ii]]$T_p= c(paramsSets$testing_base[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_base[[ii]]$omega_p= c(paramsSets$prep_base[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_base[[ii]]$IM= c(paramsSets$immigrants_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$IM[1])
parasets_lists_base[[ii]]$EM= c(paramsSets$emigrants_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$EM[1])
parasets_lists_base[[ii]]$Death= c(paramsSets$Deaths_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$Death[1])
parasets_lists_base[[ii]]$tau= c(paramsSets$tau_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$tau0)
parasets_lists_base[[ii]]$sigma= c(paramsSets$sigma_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$sigma0)


initial_state_values_sim_base[[ii]]<-as.list(c(N=parasets_lists_base[[ii]]$N0,  
                                    I=parasets_lists_base[[ii]]$I0,
                                    d=parasets_lists_base[[ii]]$d0))
output_sim_base[[ii]]<- SimpleHIV(times=times, 
                     state = initial_state_values_sim_base[[ii]],
                     parameters = parasets_lists_base[[ii]])

infectionresults_sim<-rbind(infectionresults_sim,data.frame( 
                       timestep = c(0:(times-1)),
                       scenarios = "Without COVID-19 impact and remain",
                       numsim = ii,
                       newHIV = output_sim_base[[ii]]$I, 
                       totalHIV = output_sim_base[[ii]]$N[1:times],
                       percentage_diagnosis = output_sim_base[[ii]]$d[1:times],
                       diagnosis = output_sim_base[[ii]]$diagnosis[1:times]))


}

output_sim_scenario3 <- vector("list", numsims)
parasets_lists_scenario3 <- vector("list", numsims)
initial_state_values_sim_scenario3<- vector("list", numsims)
##scenario Without COVID-19 impact and with prep promotion##
for (ii in 1:numsims) {
parasets_lists_scenario3[[ii]]<- c(N0= paramsSets$plhiv[ii], 
               I0=paramsSets$newinf[ii], 
               d0=paramsSets$prodiag[ii], 
               tau0=paramsSets$tau_base[((ii-1)*times+1)]*projectParams$tau0, 
               sigma0=paramsSets$sigma_base[((ii-1)*times+1)]*projectParams$sigma0 ,
               phi=paramsSets$effisupp[ii],  
               omega0= paramsSets$prep_scenario3[((ii-1)*times+1)]*projectParams$omega0, 
               epsilon_PrEP=paramsSets$effiPrEP[ii],  
               epsilon_condom=paramsSets$efficon[ii],   
               chi_0=paramsSets$condoms_scenario3[((ii-1)*times+1)]*projectParams$chi_0, 
               alpha0=paramsSets$acts_base[((ii-1)*times+1)]*projectParams$alpha0,  
               T= paramsSets$testing_base[((ii-1)*times+1)]*projectParams$T)
parasets_lists_scenario3[[ii]]$beta0 <- betaoption1(parameters = parasets_lists_scenario3[[ii]])
parasets_lists_scenario3[[ii]]$alpha_t=c(paramsSets$acts_base[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_scenario3[[ii]]$chi_t= c(paramsSets$condoms_scenario3[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_scenario3[[ii]]$T_p= c(paramsSets$testing_base[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_scenario3[[ii]]$omega_p= c(paramsSets$prep_scenario3[((ii-1)*times+1):((ii-1)*times+times)])
parasets_lists_scenario3[[ii]]$IM= c(paramsSets$immigrants_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$IM[1])
parasets_lists_scenario3[[ii]]$EM= c(paramsSets$emigrants_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$EM[1])
parasets_lists_scenario3[[ii]]$Death= c(paramsSets$Deaths_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$Death[1])
parasets_lists_scenario3[[ii]]$tau= c(paramsSets$tau_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$tau0)
parasets_lists_scenario3[[ii]]$sigma= c(paramsSets$sigma_base[((ii-1)*times+1):((ii-1)*times+times)]*projectParams$sigma0)


initial_state_values_sim_scenario3[[ii]]<-as.list(c(N=parasets_lists_scenario3[[ii]]$N0,  
                                    I=parasets_lists_scenario3[[ii]]$I0,
                                    d=parasets_lists_scenario3[[ii]]$d0))
output_sim_scenario3[[ii]]<- SimpleHIV(times=times, 
                     state = initial_state_values_sim_scenario3[[ii]],
                     parameters = parasets_lists_scenario3[[ii]])

infectionresults_sim<-rbind(infectionresults_sim,data.frame( 
                       timestep = c(0:(times-1)),
                       scenarios = "Without COVID-19 impact and with prep promotion",
                       numsim = ii,
                       newHIV = output_sim_scenario3[[ii]]$I, 
                       totalHIV = output_sim_scenario3[[ii]]$N[1:times],
                       percentage_diagnosis = output_sim_scenario3[[ii]]$d[1:times],
                       diagnosis = output_sim_scenario3[[ii]]$diagnosis[1:times]))


}


###add a column of cumulated number of new infections and a column of cumulated number of diagnosis
infectionresults_sim<- infectionresults_sim %>% 
  mutate(infection1 = ifelse(timestep==0,0,newHIV)) %>% group_by(scenarios,numsim) %>% mutate(csum_infection = cumsum(infection1))
infectionresults_sim<- infectionresults_sim %>% 
  mutate(diagnosis1 = ifelse(timestep==0,0,diagnosis)) %>% group_by(scenarios,numsim) %>% mutate(csum_diagnosis = cumsum(diagnosis1))

###add a colum of the variable "year" to represent###
infectionresults_sim$year<-rep(c(rep(2019,1),rep(2020,12),rep(2021,12),rep(2022,8)),3000)
infectionresults_sim <- infectionresults_sim %>%
group_by(scenarios,year,numsim) %>%
  mutate(csum_year_infection=cumsum(newHIV))
infectionresults_sim <- infectionresults_sim %>%
group_by(scenarios,year,numsim) %>%
  mutate(csum_year_diagnosis=cumsum(diagnosis))
newinfections_peryear_sim <- infectionresults_sim %>%
group_by(scenarios,year,numsim) %>%
  summarise(Sum=sum(newHIV))
diagnosis_peryear_sim <- infectionresults_sim %>%
group_by(scenarios,year,numsim) %>%
  summarise(Sum=sum(diagnosis))

###create band for 95% interval in each timestep##
quantile_interval_band_newHIV<-data.frame( 
                       timestep = integer(),
                       lowerbound = numeric(),
                       upperbound = numeric(),
                       scenarios = character())
for (ii in 1:(times)) {
quantile_interval_band_newHIV<-rbind(quantile_interval_band_newHIV,data.frame(timestep = ii-1,
                   lowerbound =  quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == ii-1))$newHIV, probs = 0.025, names = FALSE),
                   upperbound = quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == ii-1))$newHIV, probs = 0.975, names = FALSE),
                   scenarios = "With COVID-19 impact"))
}


for (ii in 1:(times)) {
quantile_interval_band_newHIV<-rbind(quantile_interval_band_newHIV,data.frame(timestep = ii-1,
                   lowerbound =  quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == ii-1))$newHIV, probs = 0.025, names = FALSE),
                   upperbound = quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == ii-1))$newHIV, probs = 0.975, names = FALSE),
                   scenarios = "Without COVID-19 impact and remain"))
}

for (ii in 1:(times)) {
quantile_interval_band_newHIV<-rbind(quantile_interval_band_newHIV,data.frame(timestep = ii-1,
                   lowerbound =  quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == ii-1))$newHIV, probs = 0.025, names = FALSE),
                   upperbound = quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == ii-1))$newHIV, probs = 0.975, names = FALSE),
                   scenarios = "Without COVID-19 impact and with prep promotion"))
}

###create band for 95% interval in each timestep##
quantile_interval_band_newdiagnoses<-data.frame( 
                       timestep = integer(),
                       lowerbound = numeric(),
                       upperbound = numeric(),
                       scenarios = character())

for (ii in 1:(times)) {
quantile_interval_band_newdiagnoses<-rbind(quantile_interval_band_newdiagnoses,data.frame(timestep = ii-1,
                   lowerbound =  quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == ii-1))$diagnosis, probs = 0.025, names = FALSE),
                   upperbound = quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == ii-1))$diagnosis, probs = 0.975, names = FALSE),
                   scenarios = "With COVID-19 impact"))
}

quantile_interval_band_newdiagnoses$diagnosis<-infectionresults$diagnosis[infectionresults$scenarios == "With COVID-19 impact"]



#show all the results with 95% CI in a table
infectionresults_95CI<-data.frame( 
                       type = character(),
                       scenarios = character(),
                       value = numeric(),
                       lowerbound = numeric(),
                       upperbound = numeric()
                       )
infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "PLHIV",
                   scenarios = "Without COVID-19 impact and remain",
                   value = round((infectionresults %>% filter(scenarios =="Without COVID-19 impact and remain",timestep == 32))$totalHIV,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == 32))$totalHIV, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == 32))$totalHIV, probs = 0.975, names = FALSE),0)))
                                                                
infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "PLHIV",
                   scenarios = "Without COVID-19 impact and with prep promotion",
                   value = round((infectionresults %>% filter(scenarios =="Without COVID-19 impact and with prep promotion",timestep == 32))$totalHIV,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == 32))$totalHIV, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == 32))$totalHIV, probs = 0.975, names = FALSE),0)))

infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "PLHIV",
                   scenarios = "With COVID-19 impact",
                   value = round((infectionresults %>% filter(scenarios =="With COVID-19 impact",timestep == 32))$totalHIV,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == 32))$totalHIV, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == 32))$totalHIV, probs = 0.975, names = FALSE),0)))

infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "cumulative infections",
                   scenarios = "Without COVID-19 impact and remain",
                   value = round((infectionresults %>% filter(scenarios =="Without COVID-19 impact and remain",timestep == 32))$csum_infection,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == 32))$csum_infection, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == 32))$csum_infection, probs = 0.975, names = FALSE),0)))

infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "cumulative infections",
                   scenarios = "Without COVID-19 impact and with prep promotion",
                   value = round((infectionresults %>% filter(scenarios =="Without COVID-19 impact and with prep promotion",timestep == 32))$csum_infection,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == 32))$csum_infection, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == 32))$csum_infection, probs = 0.975, names = FALSE),0)))

infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "cumulative infections",
                   scenarios = "With COVID-19 impact",
                   value = round((infectionresults %>% filter(scenarios =="With COVID-19 impact",timestep == 32))$csum_infection,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == 32))$csum_infection, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == 32))$csum_infection, probs = 0.975, names = FALSE),0)))

infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "cumulative diagnosis",
                   scenarios = "Without COVID-19 impact and remain",
                   value = round((infectionresults %>% filter(scenarios =="Without COVID-19 impact and remain",timestep == 32))$csum_diagnosis,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == 32))$csum_diagnosis, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and remain", timestep == 32))$csum_diagnosis, probs = 0.975, names = FALSE),0)))

infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "cumulative diagnosis",
                   scenarios = "Without COVID-19 impact and with prep promotion",
                   value = round((infectionresults %>% filter(scenarios =="Without COVID-19 impact and with prep promotion",timestep == 32))$csum_diagnosis,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == 32))$csum_diagnosis, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", timestep == 32))$csum_diagnosis, probs = 0.975, names = FALSE),0)))

infectionresults_95CI<-rbind(infectionresults_95CI,data.frame(type = "cumulative diagnosis",
                   scenarios = "With COVID-19 impact",
                   value = round((infectionresults %>% filter(scenarios =="With COVID-19 impact",timestep == 32))$csum_diagnosis,0),
                   lowerbound = round(quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == 32))$csum_diagnosis, probs = 0.025, names = FALSE),0),
                   upperbound = round(quantile((infectionresults_sim %>% filter(scenarios == "With COVID-19 impact", timestep == 32))$csum_diagnosis, probs = 0.975, names = FALSE),0)))


###number of new infections and diagnoses each year with 95% percentile interval###

newinfectionresults_peryear_95PI<-data.frame( 
                       year = integer(),
                       scenarios = character(),
                       newHIV_value = numeric(),
                       newHIV_lower = numeric(),
                       newHIV_upper = numeric(),
                       diagnosis_value = numeric(),
                       diagnosis_lower = numeric(),
                       diagnosis_upper = numeric())

for (ii in 2020:2022) {
newinfectionresults_peryear_95PI<-rbind(newinfectionresults_peryear_95PI,data.frame(
                                        year = ii,
                                        scenarios = "Without COVID-19 impact and remain",
                                        newHIV_value = round((newinfections_peryear %>% filter(scenarios =="Without COVID-19 impact and remain",year == ii))$Sum,0),
                                        newHIV_lower = round(quantile((newinfections_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and remain", year ==ii))$Sum, probs = 0.025, names = FALSE),0),
                                        newHIV_upper = round(quantile((newinfections_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and remain", year ==ii))$Sum, probs = 0.975, names = FALSE),0),
                                        diagnosis_value = round((diagnosis_peryear %>% filter(scenarios =="Without COVID-19 impact and remain",year == ii))$Sum,0),
                                        diagnosis_lower = round(quantile((diagnosis_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and remain", year ==ii))$Sum, probs = 0.025, names = FALSE),0),
                                        diagnosis_upper = round(quantile((diagnosis_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and remain", year ==ii))$Sum, probs = 0.975, names = FALSE),0)))
}

for (ii in 2020:2022) {
newinfectionresults_peryear_95PI<-rbind(newinfectionresults_peryear_95PI,data.frame(
                                        year = ii,
                                        scenarios = "With COVID-19 impact",
                                        newHIV_value = round((newinfections_peryear %>% filter(scenarios =="With COVID-19 impact",year == ii))$Sum,0),
                                        newHIV_lower = round(quantile((newinfections_peryear_sim %>% filter(scenarios == "With COVID-19 impact", year ==ii))$Sum, probs = 0.025, names = FALSE),0),
                                        newHIV_upper = round(quantile((newinfections_peryear_sim %>% filter(scenarios == "With COVID-19 impact", year ==ii))$Sum, probs = 0.975, names = FALSE),0),
                                        diagnosis_value = round((diagnosis_peryear %>% filter(scenarios =="With COVID-19 impact",year == ii))$Sum,0),
                                        diagnosis_lower = round(quantile((diagnosis_peryear_sim %>% filter(scenarios == "With COVID-19 impact", year ==ii))$Sum, probs = 0.025, names = FALSE),0),
                                        diagnosis_upper = round(quantile((diagnosis_peryear_sim %>% filter(scenarios == "With COVID-19 impact", year ==ii))$Sum, probs = 0.975, names = FALSE),0)))
}

for (ii in 2020:2022) {
newinfectionresults_peryear_95PI<-rbind(newinfectionresults_peryear_95PI,data.frame(
                                        year = ii,
                                        scenarios = "Without COVID-19 impact and with prep promotion",
                                        newHIV_value = round((newinfections_peryear %>% filter(scenarios =="Without COVID-19 impact and with prep promotion",year == ii))$Sum,0),
                                        newHIV_lower = round(quantile((newinfections_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", year ==ii))$Sum, probs = 0.025, names = FALSE),0),
                                        newHIV_upper = round(quantile((newinfections_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", year ==ii))$Sum, probs = 0.975, names = FALSE),0),
                                        diagnosis_value = round((diagnosis_peryear %>% filter(scenarios =="Without COVID-19 impact and with prep promotion",year == ii))$Sum,0),
                                        diagnosis_lower = round(quantile((diagnosis_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", year ==ii))$Sum, probs = 0.025, names = FALSE),0),
                                        diagnosis_upper = round(quantile((diagnosis_peryear_sim %>% filter(scenarios == "Without COVID-19 impact and with prep promotion", year ==ii))$Sum, probs = 0.975, names = FALSE),0)))
}

adjustmentvalue_diagnosis_2022<-1#2/8
newinfectionresults_peryear_95PI$diagnosis_value <- ifelse(newinfectionresults_peryear_95PI$year %in% c("2022"), newinfectionresults_peryear_95PI$diagnosis_value*adjustmentvalue_diagnosis_2022, newinfectionresults_peryear_95PI$diagnosis_value)

newinfectionresults_peryear_95PI$diagnosis_lower <- ifelse(newinfectionresults_peryear_95PI$year %in% c("2022"), newinfectionresults_peryear_95PI$diagnosis_lower*adjustmentvalue_diagnosis_2022, newinfectionresults_peryear_95PI$diagnosis_lower)

newinfectionresults_peryear_95PI$diagnosis_upper <- ifelse(newinfectionresults_peryear_95PI$year %in% c("2022"), newinfectionresults_peryear_95PI$diagnosis_upper*adjustmentvalue_diagnosis_2022, newinfectionresults_peryear_95PI$diagnosis_upper)

newinfectionresults_peryear_95PI$newHIV_value <- ifelse(newinfectionresults_peryear_95PI$year %in% c("2022"), newinfectionresults_peryear_95PI$newHIV_value*adjustmentvalue_diagnosis_2022, newinfectionresults_peryear_95PI$newHIV_value)

newinfectionresults_peryear_95PI$newHIV_lower <- ifelse(newinfectionresults_peryear_95PI$year %in% c("2022"), newinfectionresults_peryear_95PI$newHIV_lower*adjustmentvalue_diagnosis_2022, newinfectionresults_peryear_95PI$newHIV_lower)

newinfectionresults_peryear_95PI$newHIV_upper <- ifelse(newinfectionresults_peryear_95PI$year %in% c("2022"), newinfectionresults_peryear_95PI$newHIV_upper*adjustmentvalue_diagnosis_2022, newinfectionresults_peryear_95PI$newHIV_upper)

newinfectionresults_peryear_95PI
quantile_interval_band_newHIV$newHIV<-infectionresults$newHIV


#### Function to calculate percentage reduction with 95% PI for main scenarios####
calculate_main_reduction_with_PI <- function(baseline_scenario, comparison_scenario, outcome_var, timepoint = 32) {
  
  # Get baseline values (Without COVID-19 impact and remain)
  baseline_data <- infectionresults_sim %>% 
    filter(scenarios == baseline_scenario, timestep == timepoint)
  
  # Get comparison values 
  comparison_data <- infectionresults_sim %>% 
    filter(scenarios == comparison_scenario, timestep == timepoint)
  
  # Calculate percentage reduction for each simulation
  baseline_values <- baseline_data[[outcome_var]]
  comparison_values <- comparison_data[[outcome_var]]
  
  # Calculate percentage change: (comparison - baseline) / baseline * 100
  percent_changes <- (comparison_values - baseline_values) / baseline_values * 100
  
  # Calculate absolute difference in cases
  case_differences <- comparison_values - baseline_values
  
  # Calculate summary statistics
  median_percent <- median(percent_changes)
  pi_025_percent <- quantile(percent_changes, 0.025)
  pi_975_percent <- quantile(percent_changes, 0.975)
  
  median_cases <- median(case_differences)
  pi_025_cases <- quantile(case_differences, 0.025)
  pi_975_cases <- quantile(case_differences, 0.975)
  
  return(list(
    percent_reduction = list(
      median = round(median_percent, 1),
      pi_025 = round(pi_025_percent, 1),
      pi_975 = round(pi_975_percent, 1)
    ),
    case_difference = list(
      median = round(median_cases, 0),
      pi_025 = round(pi_025_cases, 0),
      pi_975 = round(pi_975_cases, 0)
    )
  ))
}

# Function to calculate yearly statistics with 95% PI
calculate_yearly_stats_with_PI <- function(scenario_name, target_year) {
  # Get data for the last timestep of the target year
  if (target_year == 2020) {
    target_timestep <- 12  # December 2020
  } else if (target_year == 2021) {
    target_timestep <- 24  # December 2021
  } else if (target_year == 2022) {
    target_timestep <- 32  # August 2022
  }
  
  data <- infectionresults_sim %>% 
    filter(scenarios == scenario_name, timestep == target_timestep)
  
  csum_infection_stats <- list(
    median = round(median(data$csum_infection), 0),
    pi_025 = round(quantile(data$csum_infection, 0.025), 0),
    pi_975 = round(quantile(data$csum_infection, 0.975), 0)
  )
  
  return(list(
    csum_infection = csum_infection_stats
  ))
}

# Calculate yearly statistics for 2020 comparison
no_covid_2020 <- calculate_yearly_stats_with_PI("Without COVID-19 impact and remain", 2020)
covid_2020 <- calculate_yearly_stats_with_PI("With COVID-19 impact", 2020)

# Calculate 2020 percentage reduction
covid_2020_data <- infectionresults_sim %>% 
  filter(scenarios == "With COVID-19 impact", timestep == 12)
no_covid_2020_data <- infectionresults_sim %>% 
  filter(scenarios == "Without COVID-19 impact and remain", timestep == 12)

covid_2020_percent_changes <- (covid_2020_data$csum_infection - no_covid_2020_data$csum_infection) / no_covid_2020_data$csum_infection * 100

covid_2020_reduction <- list(
  median = round(median(covid_2020_percent_changes), 1),
  pi_025 = round(quantile(covid_2020_percent_changes, 0.025), 1),
  pi_975 = round(quantile(covid_2020_percent_changes, 0.975), 1)
)

# Function to format results for manuscript
format_main_result <- function(median_val, pi_025, pi_975, is_percent = TRUE) {
  if (is_percent) {
    if (median_val < 0) {
      return(paste0(abs(median_val), "% [95% PI: ", abs(pi_975), "–", abs(pi_025), "%]"))
    } else {
      return(paste0(median_val, "% [95% PI: ", pi_025, "–", pi_975, "%]"))
    }
  } else {
    return(paste0(median_val, " [95% PI: ", pi_025, "–", pi_975, "]"))
  }
}

# Define main scenarios
main_scenarios <- c(
  "Without COVID-19 impact and remain",
  "With COVID-19 impact", 
  "Without COVID-19 impact and with prep promotion"
)

main_scenario_names <- c(
  "No COVID-19 scenario",
  "COVID-19 scenario",
  "No COVID-19 plus PrEP scenario"
)

# Calculate percentage reductions
# COVID-19 vs No COVID-19
covid_infection_reduction <- calculate_main_reduction_with_PI(
  "Without COVID-19 impact and remain", 
  "With COVID-19 impact", 
  "csum_infection"
)

covid_diagnosis_reduction <- calculate_main_reduction_with_PI(
  "Without COVID-19 impact and remain", 
  "With COVID-19 impact", 
  "csum_diagnosis"
)

# PrEP scenario vs No COVID-19
prep_infection_reduction <- calculate_main_reduction_with_PI(
  "Without COVID-19 impact and remain", 
  "Without COVID-19 impact and with prep promotion", 
  "csum_infection"
)

prep_diagnosis_reduction <- calculate_main_reduction_with_PI(
  "Without COVID-19 impact and remain", 
  "Without COVID-19 impact and with prep promotion", 
  "csum_diagnosis"
)

covid_totalhiv_reduction <- calculate_main_reduction_with_PI(
  "Without COVID-19 impact and remain", 
  "With COVID-19 impact", 
  "totalHIV"
)

prep_totalhiv_reduction <- calculate_main_reduction_with_PI(
  "Without COVID-19 impact and remain", 
  "Without COVID-19 impact and with prep promotion", 
  "totalHIV"
)

prep_infection_reduction_lastmonth <- calculate_main_reduction_with_PI(
  "Without COVID-19 impact and remain", 
  "Without COVID-19 impact and with prep promotion", 
  "newHIV"
)

# Create percentage of changes of cumulative infections and diagnoses with 95% PI table
reductions_table <- data.frame(
  Comparison = character(),
  Outcome = character(),
  Percent_Reduction_Median = numeric(),
  Percent_Reduction_PI_025 = numeric(),
  Percent_Reduction_PI_975 = numeric(),
  Case_Difference_Median = numeric(),
  Case_Difference_PI_025 = numeric(),
  Case_Difference_PI_975 = numeric(),
  Formatted_Percentage = character(),
  Formatted_Cases = character(),
  stringsAsFactors = FALSE
)

# Add COVID-19 vs No COVID-19 comparisons
reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "COVID-19 vs No COVID-19",
  Outcome = "Cumulative Infections",
  Percent_Reduction_Median = covid_infection_reduction$percent_reduction$median,
  Percent_Reduction_PI_025 = covid_infection_reduction$percent_reduction$pi_025,
  Percent_Reduction_PI_975 = covid_infection_reduction$percent_reduction$pi_975,
  Case_Difference_Median = covid_infection_reduction$case_difference$median,
  Case_Difference_PI_025 = covid_infection_reduction$case_difference$pi_025,
  Case_Difference_PI_975 = covid_infection_reduction$case_difference$pi_975,
  Formatted_Percentage = format_main_result(abs(covid_infection_reduction$percent_reduction$median), 
                                           abs(covid_infection_reduction$percent_reduction$pi_975), 
                                           abs(covid_infection_reduction$percent_reduction$pi_025), TRUE),
  Formatted_Cases = format_main_result(abs(covid_infection_reduction$case_difference$median), 
                                      abs(covid_infection_reduction$case_difference$pi_975), 
                                      abs(covid_infection_reduction$case_difference$pi_025), FALSE)
))

reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "COVID-19 vs No COVID-19",
  Outcome = "Cumulative Diagnoses",
  Percent_Reduction_Median = covid_diagnosis_reduction$percent_reduction$median,
  Percent_Reduction_PI_025 = covid_diagnosis_reduction$percent_reduction$pi_025,
  Percent_Reduction_PI_975 = covid_diagnosis_reduction$percent_reduction$pi_975,
  Case_Difference_Median = covid_diagnosis_reduction$case_difference$median,
  Case_Difference_PI_025 = covid_diagnosis_reduction$case_difference$pi_025,
  Case_Difference_PI_975 = covid_diagnosis_reduction$case_difference$pi_975,
  Formatted_Percentage = format_main_result(abs(covid_diagnosis_reduction$percent_reduction$median), 
                                           abs(covid_diagnosis_reduction$percent_reduction$pi_975), 
                                           abs(covid_diagnosis_reduction$percent_reduction$pi_025), TRUE),
  Formatted_Cases = format_main_result(abs(covid_diagnosis_reduction$case_difference$median), 
                                      abs(covid_diagnosis_reduction$case_difference$pi_975), 
                                      abs(covid_diagnosis_reduction$case_difference$pi_025), FALSE)
))


# Add PrEP vs No COVID-19 comparisons
reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "PrEP vs No COVID-19",
  Outcome = "Cumulative Infections",
  Percent_Reduction_Median = prep_infection_reduction$percent_reduction$median,
  Percent_Reduction_PI_025 = prep_infection_reduction$percent_reduction$pi_025,
  Percent_Reduction_PI_975 = prep_infection_reduction$percent_reduction$pi_975,
  Case_Difference_Median = prep_infection_reduction$case_difference$median,
  Case_Difference_PI_025 = prep_infection_reduction$case_difference$pi_025,
  Case_Difference_PI_975 = prep_infection_reduction$case_difference$pi_975,
  Formatted_Percentage = format_main_result(abs(prep_infection_reduction$percent_reduction$median), 
                                           abs(prep_infection_reduction$percent_reduction$pi_975), 
                                           abs(prep_infection_reduction$percent_reduction$pi_025), TRUE),
  Formatted_Cases = format_main_result(abs(prep_infection_reduction$case_difference$median), 
                                      abs(prep_infection_reduction$case_difference$pi_975), 
                                      abs(prep_infection_reduction$case_difference$pi_025), FALSE)
))

reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "PrEP vs No COVID-19",
  Outcome = "Cumulative Diagnoses",
  Percent_Reduction_Median = prep_diagnosis_reduction$percent_reduction$median,
  Percent_Reduction_PI_025 = prep_diagnosis_reduction$percent_reduction$pi_025,
  Percent_Reduction_PI_975 = prep_diagnosis_reduction$percent_reduction$pi_975,
  Case_Difference_Median = prep_diagnosis_reduction$case_difference$median,
  Case_Difference_PI_025 = prep_diagnosis_reduction$case_difference$pi_025,
  Case_Difference_PI_975 = prep_diagnosis_reduction$case_difference$pi_975,
  Formatted_Percentage = format_main_result(abs(prep_diagnosis_reduction$percent_reduction$median), 
                                           abs(prep_diagnosis_reduction$percent_reduction$pi_975), 
                                           abs(prep_diagnosis_reduction$percent_reduction$pi_025), TRUE),
  Formatted_Cases = format_main_result(abs(prep_diagnosis_reduction$case_difference$median), 
                                      abs(prep_diagnosis_reduction$case_difference$pi_975), 
                                      abs(prep_diagnosis_reduction$case_difference$pi_025), FALSE)
))

reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "COVID-19 vs No COVID-19",
  Outcome = "Total HIV",
  Percent_Reduction_Median = covid_totalhiv_reduction$percent_reduction$median,
  Percent_Reduction_PI_025 = covid_totalhiv_reduction$percent_reduction$pi_025,
  Percent_Reduction_PI_975 = covid_totalhiv_reduction$percent_reduction$pi_975,
  Case_Difference_Median = covid_totalhiv_reduction$case_difference$median,
  Case_Difference_PI_025 = covid_totalhiv_reduction$case_difference$pi_025,
  Case_Difference_PI_975 = covid_totalhiv_reduction$case_difference$pi_975,
  Formatted_Percentage = if(covid_totalhiv_reduction$percent_reduction$median < 0) {
    format_main_result(abs(covid_totalhiv_reduction$percent_reduction$median), 
                       abs(covid_totalhiv_reduction$percent_reduction$pi_975), 
                       abs(covid_totalhiv_reduction$percent_reduction$pi_025), TRUE)
  } else {
    format_main_result(covid_totalhiv_reduction$percent_reduction$median, 
                       covid_totalhiv_reduction$percent_reduction$pi_025, 
                       covid_totalhiv_reduction$percent_reduction$pi_975, TRUE)
  },
  Formatted_Cases = if(covid_totalhiv_reduction$case_difference$median < 0) {
    format_main_result(abs(covid_totalhiv_reduction$case_difference$median), 
                       abs(covid_totalhiv_reduction$case_difference$pi_975), 
                       abs(covid_totalhiv_reduction$case_difference$pi_025), FALSE)
  } else {
    format_main_result(covid_totalhiv_reduction$case_difference$median, 
                       covid_totalhiv_reduction$case_difference$pi_025, 
                       covid_totalhiv_reduction$case_difference$pi_975, FALSE)
  }
))

reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "PrEP vs No COVID-19",
  Outcome = "Total HIV",
  Percent_Reduction_Median = prep_totalhiv_reduction$percent_reduction$median,
  Percent_Reduction_PI_025 = prep_totalhiv_reduction$percent_reduction$pi_025,
  Percent_Reduction_PI_975 = prep_totalhiv_reduction$percent_reduction$pi_975,
  Case_Difference_Median = prep_totalhiv_reduction$case_difference$median,
  Case_Difference_PI_025 = prep_totalhiv_reduction$case_difference$pi_025,
  Case_Difference_PI_975 = prep_totalhiv_reduction$case_difference$pi_975,
  Formatted_Percentage = if(prep_totalhiv_reduction$percent_reduction$median < 0) {
    format_main_result(abs(prep_totalhiv_reduction$percent_reduction$median), 
                       abs(prep_totalhiv_reduction$percent_reduction$pi_975), 
                       abs(prep_totalhiv_reduction$percent_reduction$pi_025), TRUE)
  } else {
    format_main_result(prep_totalhiv_reduction$percent_reduction$median, 
                       prep_totalhiv_reduction$percent_reduction$pi_025, 
                       prep_totalhiv_reduction$percent_reduction$pi_975, TRUE)
  },
  Formatted_Cases = if(prep_totalhiv_reduction$case_difference$median < 0) {
    format_main_result(abs(prep_totalhiv_reduction$case_difference$median), 
                       abs(prep_totalhiv_reduction$case_difference$pi_975), 
                       abs(prep_totalhiv_reduction$case_difference$pi_025), FALSE)
  } else {
    format_main_result(prep_totalhiv_reduction$case_difference$median, 
                       prep_totalhiv_reduction$case_difference$pi_025, 
                       prep_totalhiv_reduction$case_difference$pi_975, FALSE)
  }
))


# Add 2020-specific reduction
reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "COVID-19 vs No COVID-19",
  Outcome = "2020 Infections Only",
  Percent_Reduction_Median = covid_2020_reduction$median,
  Percent_Reduction_PI_025 = covid_2020_reduction$pi_025,
  Percent_Reduction_PI_975 = covid_2020_reduction$pi_975,
  Case_Difference_Median = covid_2020$csum_infection$median - no_covid_2020$csum_infection$median,
  Case_Difference_PI_025 = quantile(covid_2020_data$csum_infection - no_covid_2020_data$csum_infection, 0.025),
  Case_Difference_PI_975 = quantile(covid_2020_data$csum_infection - no_covid_2020_data$csum_infection, 0.975),
  Formatted_Percentage = format_main_result(abs(covid_2020_reduction$median), 
                                           abs(covid_2020_reduction$pi_975), 
                                           abs(covid_2020_reduction$pi_025), TRUE),
  Formatted_Cases = format_main_result(abs(covid_2020$csum_infection$median - no_covid_2020$csum_infection$median), 
                                      abs(round(quantile(covid_2020_data$csum_infection - no_covid_2020_data$csum_infection, 0.975), 0)), 
                                      abs(round(quantile(covid_2020_data$csum_infection - no_covid_2020_data$csum_infection, 0.025), 0)), FALSE)
))

reductions_table <- rbind(reductions_table, data.frame(
  Comparison = "PrEP vs No COVID-19",
  Outcome = "Last month Infections",
  Percent_Reduction_Median = prep_infection_reduction_lastmonth$percent_reduction$median,
  Percent_Reduction_PI_025 = prep_infection_reduction_lastmonth$percent_reduction$pi_025,
  Percent_Reduction_PI_975 = prep_infection_reduction_lastmonth$percent_reduction$pi_975,
  Case_Difference_Median = prep_infection_reduction_lastmonth$case_difference$median,
  Case_Difference_PI_025 = prep_infection_reduction_lastmonth$case_difference$pi_025,
  Case_Difference_PI_975 = prep_infection_reduction_lastmonth$case_difference$pi_975,
  Formatted_Percentage = format_main_result(abs(prep_infection_reduction_lastmonth$percent_reduction$median), 
                                           abs(prep_infection_reduction_lastmonth$percent_reduction$pi_975), 
                                           abs(prep_infection_reduction_lastmonth$percent_reduction$pi_025), TRUE),
  Formatted_Cases = format_main_result(abs(prep_infection_reduction_lastmonth$case_difference$median), 
                                      abs(prep_infection_reduction_lastmonth$case_difference$pi_975), 
                                      abs(prep_infection_reduction_lastmonth$case_difference$pi_025), FALSE)
))

#Save output in some form Rda file and/or csv
# If file not already created make sure it is not overwritten
if (!file.exists(file.path(resultsFolder, "infectionresults_sim_20250612.csv"))) {
write.csv(infectionresults_sim, file = file.path(resultsFolder, "infectionresults_sim_20250612.csv"))
}
if (!file.exists(file.path(resultsFolder, "summarized_results_95PI_20250612.csv"))) {
write.csv(infectionresults_95CI, file = file.path(resultsFolder, "summarized_results_95PI_20250612.csv"))
}
if (!file.exists(file.path(resultsFolder, "monthly_results_95PI_20250612.csv"))) {
write.csv(quantile_interval_band_newHIV, file = file.path(resultsFolder, "monthly_results_95PI_20250612.csv"))
}
if (!file.exists(file.path(resultsFolder, "yearly_cumulative_results_95PI_20250612.csv"))) {
write.csv(newinfectionresults_peryear_95PI, file = file.path(resultsFolder, "yearly_cumulative_results_95PI_20250612.csv"))
}


```

