# 2_Generate_figures.Rmd#

This script is to generate figures for Simple HIV model.

```{r Generate figures for number of new infections}
#basePath <- getwd()
#source(file.path(basePath, "1_input and run model.Rmd"))
library(ggplot2)
library(gridExtra)
library(RColorBrewer)
library(stringr)
library(tidyverse)
library(cowplot)
###generate figure for number of new infections### 
##The optimal result##
newinfectionfig<-ggplot(data = newinfectionresults,          
  aes(x = timestep, y = newHIV, colour = scenarios, group = scenarios)) +  
  geom_line() +          
  xlab(paste0("Time (", projectSpecs$stepsize, ")"))+    # add label for x axis
  ylab("Number of new HIV infections") +
  labs(title = paste("Impact of different scenarios on HIV epidemic"))+
  scale_x_continuous(breaks = c(1,7,13,19,25,31), 
                     labels = c("Jan-2020","July-2020","Jan-2021","July-2021","Jan-2022","July-2022"))+
  ylim(0,signif(max(newinfectionresults$newHIV)*2,1))

newinfectionfig

##Simulation results##
newinfectionfig_sim<- ggplot(data = infectionresults_sim_filter_newHIV, aes(x = timestep, y = newHIV, 
  colour = scenarios, fill = scenarios, group = interaction(scenarios, numsim)))+
geom_line() +
   #geom_ribbon(aes(ymin = quantile(newHIV, 0.025), 
    # ymax = quantile(newHIV, 0.975))) + 
  geom_line(data = (infectionresults %>% filter(scenarios == "Without COVID-19 impact and remain")), 
    aes(group = 1), colour = "blue", size = 1.1) +
  geom_line(data = (infectionresults %>% filter(scenarios == "With COVID-19 impact")), 
    aes(group = 1), colour = "black", size = 1.1) +
  geom_line(data = (infectionresults %>% filter(scenarios == "Without COVID-19 impact and with prep promotion")), 
    aes(group = 1), colour = "green", size = 1.1) +
  expand_limits(y = c(0, NA)) + 
  scale_x_continuous(breaks = c(1,7,13,19,25,31), 
                     labels = c("Jan-2020","July-2020","Jan-2021","July-2021","Jan-2022","July-2022"))+ 
  scale_colour_manual(name = "", 
    breaks = c("Without COVID-19 impact and remain", "With COVID-19 impact","Without COVID-19 impact and with prep promotion"), 
    values = c("cornflowerblue", "gray","#CCFFE5"),
    labels = c("Without COVID-19 pandemic", "With COVID-19 pandemic","With PrEP promotion")) +
  xlab(paste0("Time (", projectSpecs$stepsize, ")")) + ylab("Number of new HIV infections") 
newinfectionfig_sim<- newinfectionfig_sim+ theme_classic()
newinfectionfig_sim

##Simulation results with band##
quantile_interval_band_newHIV$newHIV<-infectionresults$newHIV
newinfectionfig_sim_band<- ggplot()+
  
  geom_smooth(data = quantile_interval_band_newHIV, 
              aes(x = timestep, y = newHIV,
              min = lowerbound, ymax = upperbound, 
              fill = scenarios, colour = scenarios
              ),alpha = 0.2,
              stat = "identity") +
  geom_line(size = 1.2) +
  scale_colour_manual(name = "", 
    breaks = c("With COVID-19 impact","Without COVID-19 impact and remain", "Without COVID-19 impact and with prep promotion"), 
    values = c("#FC8D62","#66C2A5",  "#8DA0CB"),
    labels = c("COVID-19","No COVID-19","No COVID-19 plus PrEP")) +
  scale_fill_manual(name = "", 
    breaks = c("With COVID-19 impact","Without COVID-19 impact and remain", "Without COVID-19 impact and with prep promotion"), 
    values = c("#FC8D62","#66C2A5",  "#8DA0CB"),
    labels = c("COVID-19","No COVID-19","No COVID-19 plus PrEP"))+
  scale_x_continuous(breaks = c(1,7,13,19,25,31), 
                     labels = c("Jan-2020","July-2020","Jan-2021","July-2021","Jan-2022","July-2022"))+ 
  xlab(paste0("Time (", projectSpecs$stepsize, ")")) + 
  ylab("Number of new HIV infections")+
  ylim(0,70)
newinfectionfig_sim_band<- newinfectionfig_sim_band+ theme_classic()
newinfectionfig_sim_band

##two scenarios##
newinfectionfig_sim_band_twoscenarios<- ggplot()+
  
  geom_smooth(data = subset(quantile_interval_band_newHIV,scenarios %in% c("Without COVID-19 impact and remain","With COVID-19 impact")), 
              aes(x = timestep, y = newHIV,
              min = lowerbound, ymax = upperbound, 
              fill = scenarios, colour = scenarios
              ),alpha = 0.2,
              stat = "identity") +
  geom_line(linewidth = 1.2) +
  scale_colour_manual(name = "", 
    breaks = c("With COVID-19 impact","Without COVID-19 impact and remain"), 
    values = c("#FC8D62","#66C2A5"),
    labels = c("With COVID-19","No COVID-19")) +
  scale_fill_manual(name = "", 
    breaks = c("With COVID-19 impact","Without COVID-19 impact and remain"), 
    values = c("#FC8D62","#66C2A5"),
    labels = c("With COVID-19","No COVID-19"))+
  scale_x_continuous(breaks = c(1,7,13,19,25,31), 
                     labels = c("Jan-2020","July-2020","Jan-2021","July-2021","Jan-2022","July-2022"))+ 
  xlab(paste0("Time (", projectSpecs$stepsize, ")")) + 
  ylab("Number of new HIV infections")+
  ylim(0,70)+ 
  theme_classic()+
  theme(legend.position = "top")+
  theme(axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.key.size = unit(1, "cm"))
  #theme(text = element_text(size=rel(3.5)))
newinfectionfig_sim_band_twoscenarios

display.brewer.all()
brewer.pal(n = 8, name = 'Set2')
###generate figure for number of cumulated new infections###
cumulatedinfectionfig<-ggplot(data = newinfectionresults,          
       aes(x = timestep, y = csum, colour = scenarios, group = scenarios)) +  
  geom_line() +                                         
  xlab(paste0("Time (", projectSpecs$stepsize, ")"))+    
  ylab("Cumulated number of new HIV infections") +
  labs(title = paste("Impact of different scenarios on HIV epidemic"))+
  scale_x_continuous(breaks = c(1,7,13,19,25,31), 
                     labels = c("Jan-2020","July-2020","Jan-2021","July-2021","Jan-2022","July-2022"))+
  ylim(0,(trunc(max(newinfectionresults$csum)/500)+1)*500)

cumulatedinfectionfig

###save figure###25，8.5 for poster
SaveFigure <- function(folder, filename, figure, 
    format = ".png", width = 25, 
    height = 8.5, units = "cm", dpi=600,...) {
    ggsave(file.path(folder, paste(filename, format, sep = "")), 
      plot = figure, width = width, height = height, units = units,dpi=dpi, ...)
}

# If figure not already created make sure it is not overwritten
if (!file.exists(file.path(figFolder, "cumulated_HIV_infection20240117.png"))) {
    SaveFigure(figFolder,"cumulated_HIV_infection20240117",cumulatedinfectionfig)
}
if (!file.exists(file.path(figFolder, "newinfectionfig_sim_band_twoscenarios20240708.png"))) {
    SaveFigure(figFolder,"newinfectionfig_sim_band_twoscenarios20240708",newinfectionfig_sim_band_twoscenarios)
}
if (!file.exists(file.path(figFolder, "newinfectionfig_sim_band_20240703.png"))) {
    SaveFigure(figFolder,"newinfectionfig_sim_band_20240703.png",newinfectionfig_sim_band)
}
```

```{r Generate figures for cumulated number of infections}
# load HIV estimates data
HIV_cascade_EstimatesdataFile<- file.path(dataFolder,  "HIVcascadeEstimates_2022.csv")
HIV_cascade_Estimatesdata<-read.csv(HIV_cascade_EstimatesdataFile,fileEncoding = 'UTF-8-BOM')
Estimatesdata<-data.frame(x = numeric(),
                       infectedHIV = numeric(),
                       infectedHIV_lower = numeric(),
                       infectedHIV_upper = numeric())
Estimatesdata<-rbind(Estimatesdata,data.frame(
                x=c(0,12,24,36),
                infectedHIV=HIV_cascade_Estimatesdata$value[40:43],
                infectedHIV_lower = HIV_cascade_Estimatesdata$lower[40:43],
                infectedHIV_upper = HIV_cascade_Estimatesdata$upper[40:43]))

###generate figure for number of total infections###
totalinfectionfig<-ggplot()+
       geom_line(aes(x = timestep, y = totalHIV, colour = scenarios, group = scenarios),data = totalinfectionresults)+
  xlab("Time (month)")+                 
  ylab("Number of PLHIV in AU") +
  labs(title = paste("Impact of different scenarios on HIV epidemic"))+
  scale_x_continuous(breaks = c(1,7,13,19,25,31), 
                     labels = c("Jan-2020","July-2020","Jan-2021","July-2021","Jan-2022","July-2022"))+
  ylim((trunc(min(Estimatesdata$infectedHIV_lower)/5000))*5000,(trunc(max(Estimatesdata$infectedHIV_upper)/5000)+1)*5000)+
  ###ylim(15000,(trunc(max(Estimatesdata$infectedHIV_upper)/5000)+1)*5000)+
  geom_line(aes(y = infectedHIV,x = x), color = "black",data = Estimatesdata)+
  geom_line(aes(y = infectedHIV_lower,x = x), color = "black",linetype = "twodash",data = Estimatesdata)+
  geom_line(aes(y = infectedHIV_upper,x = x), color = "black",linetype = "twodash",data = Estimatesdata)+
  geom_text(aes(4, 20000 , label = "estimate"), vjust= -0.2) +
  geom_text(aes(3, 25000 , label = "upper"), vjust= 0.5) +
  geom_text(aes(3, 17500 , label = "lower"), vjust= -0.3)

totalinfectionfig

##simulation results##
totalinfectionfig_sim<- ggplot(data = infectionresults_sim_filter_totalHIV, aes(x = timestep, y = totalHIV, 
  colour = scenarios, fill = scenarios, group = interaction(scenarios, numsim)))+
geom_line() +
  # geom_ribbon(aes(ymin = quantile(infected, 0.025), 
  #   ymax = quantile(infected, 0.975))) + 
  geom_line(data = (infectionresults %>% filter(scenarios == "Without COVID-19 impact and with prep promotion")), 
    aes(group = 1), colour = "green", size = 1.0) +
  geom_line(data = (infectionresults %>% filter(scenarios == "Without COVID-19 impact and remain")), 
    aes(group = 1), colour = "blue", size = 1.0) +
  geom_line(data = (infectionresults %>% filter(scenarios == "With COVID-19 impact")), 
    aes(group = 1), colour = "black", size = 1.0) +
  
  expand_limits(y = c(0, NA)) + 
  scale_x_continuous(breaks = c(1,7,13,19,25,31), 
                     labels = c("Jan-2020","July-2020","Jan-2021","July-2021","Jan-2022","July-2022"))+ 
  scale_colour_manual(name = "", 
    breaks = c("Without COVID-19 impact and remain", "With COVID-19 impact","Without COVID-19 impact and with prep promotion"), 
    values = c("cornflowerblue", "gray","#CCFFE5"),
    labels = c("Without COVID-19 pandemic", "With COVID-19 pandemic","With PrEP promotion"))+
  xlab(paste0("Time (", projectSpecs$stepsize, ")")) + ylab("Number of people living with HIV infections") 
plot+ theme(panel.background = element_blank(),
    panel.border = element_blank(), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.line = element_line(colour = "black")
    )
totalinfectionfig_sim<- totalinfectionfig_sim+ theme_classic()
totalinfectionfig_sim
# If figure not already created make sure it is not overwritten
if (!file.exists(file.path(figFolder, "total_HIV_infection20240117.png"))) {
    SaveFigure(figFolder,"total_HIV_infection20240117",totalinfectionfig)
}
if (!file.exists(file.path(figFolder, "total_HIV_infection_sim_20240305_3scenarios1.png"))) {
    SaveFigure(figFolder,"total_HIV_infection_sim_20240305_3scenarios",totalinfectionfig_sim)
}

```

```{r Generate figures for new infections and diagnosis per year}
HIV_Diagnoses_File<- file.path(dataFolder, "raw_data", "HIVdiagnoses.csv")
HIV_Diagnoses_annualdata<-read.csv(HIV_Diagnoses_File,fileEncoding = 'UTF-8-BOM')

newinfections_diagnosis_peryear_fig<- ggplot(subset(newinfectionresults_peryear_95PI,scenarios %in% c("With COVID-19 impact"))) +
       geom_line(aes(x = year, y = diagnosis_value),colour = "#f9cb45")+
       geom_point(aes(x = year, y = diagnosis_value, colour = "Diagnoses",shape = "Diagnoses"),size = 2)+ 
       #geom_errorbar(aes(x = year, ymin=diagnosis_lower,ymax=diagnosis_upper,width=0.1), colour = "#4cb1c4")+
       geom_line(aes(x = year, y = newHIV_value),colour = "#34a186")+
       geom_point(aes(x = year, y = newHIV_value, colour = "Infections",shape = "Infections"),size = 2)+
       geom_errorbar(aes(x = year, ymin=newHIV_lower,ymax=newHIV_upper,width=0.1), colour = "#34a186")+
       geom_point(aes(x = HIV_Diagnoses_annualdata$year, y = HIV_Diagnoses_annualdata$diagnosis, colour = "Diagnoses from\nSurveillance report",shape = "Diagnoses from\nSurveillance report"),size = 2)+
       geom_point(aes(x = HIV_Diagnoses_annualdata$year, y = HIV_Diagnoses_annualdata$infections, colour = "Infections from\nECDC model",shape = "Infections from\nECDC model"),size = 2)+
       geom_errorbar(aes(x = HIV_Diagnoses_annualdata$year, ymin=HIV_Diagnoses_annualdata$infections_lower,ymax=HIV_Diagnoses_annualdata$infections_upper,width=0.1), colour = "#4cb1c4")+
       scale_colour_manual(name="Type",breaks = c("Diagnoses", "Infections","Diagnoses from\nSurveillance report","Infections from\nECDC model"),labels = c("Diagnoses", "Infections","Diagnoses from\nSurveillance report","Infections from\nECDC model" ), values = c("#f9cb45","#34a186","#b5182b","#4cb1c4")) +
       scale_shape_manual(name="Type",breaks = c("Diagnoses", "Infections","Diagnoses from\nSurveillance report","Infections from\nECDC model"),labels = c("Diagnoses", "Infections","Diagnoses from\nSurveillance report","Infections from\nECDC model" ), values = c(16,16,17,17)) +
       ylim(0,signif(max(newinfectionresults_peryear_95PI$diagnosis_upper),1)) +
       #scale_y_continuous(expand = c(0, 200), limits = c(0, NA))+
       scale_x_continuous(breaks = c(2020,2021,2022), 
                     labels = c("2020","2021","2022"))+ 
       xlab("Year") + ylab("Number") 
newinfections_diagnosis_peryear_fig<- newinfections_diagnosis_peryear_fig+ theme_classic()
newinfections_diagnosis_peryear_fig
#grid.arrange(newinfections_diagnosis_peryear_fig, newinfectionfig_sim_band, nrow=2)





diagnosis_peryear_fig<- ggplot(subset(newinfectionresults_peryear_95PI,scenarios %in% c("With COVID-19 impact"))) +
       geom_bar(aes(x = c(2019.8,2020.8,2021.8), y = diagnosis_value, fill = "Diagnoses",colour = "Diagnoses"), stat="identity",  width=0.4, alpha = 0.5)+ 
       geom_errorbar(aes(x = c(2019.8,2020.8,2021.8), ymin=diagnosis_lower,ymax=diagnosis_upper,width=0.1), colour = "#b5182b")+
       geom_bar(aes(x = c(2020.2,2021.2,2022.2), y = HIV_Diagnoses_annualdata$diagnosis, fill = "Notifications from\nSurveillance report", colour = "Notifications from\nSurveillance report"), stat="identity", width=0.4, alpha = 0.5)+
       scale_colour_manual(name="",breaks = c("Diagnoses", "Notifications from\nSurveillance report"),labels = c("Diagnoses from\nour model", "Diagnoses from\nSurveillance report"), values = c('#b5182b80','#f9cb4580'))+
       scale_fill_manual(name="",breaks = c("Diagnoses", "Notifications from\nSurveillance report"),labels = c("Diagnoses from\nour model", "Diagnoses from\nSurveillance report"), values = c('#b5182b80','#f9cb4580'))+
       ylim(0,signif(max(newinfectionresults_peryear_95PI$diagnosis_upper),1)) +
       #scale_y_continuous(expand = c(0, 200), limits = c(0, NA))+
       scale_x_continuous(breaks = c(2020,2021,2022), 
                     labels = c("2020","2021","2022"))+ 
       xlab("Year") + ylab("Number") +
       theme_classic() +
  theme(legend.position = "top")+
  theme(axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.key.size = unit(1, "cm"))#+
       #theme(plot.margin = margin(30, 0, 0, 30))+
       #labs(tag = "  \n A") +
       #theme(plot.tag.position = c(-0.02, 0.7))
             
diagnosis_peryear_fig

newinfections_peryear_fig<- ggplot(subset(newinfectionresults_peryear_95PI,scenarios %in% c("With COVID-19 impact"))) +
       geom_bar(aes(x = c(2019.8,2020.8,2021.8), y = newHIV_value, fill = "Infections",colour = "Infections"), stat="identity",  width=0.4, alpha = 0.5)+ 
       geom_errorbar(aes(x = c(2019.8,2020.8,2021.8), ymin=newHIV_lower,ymax=newHIV_upper,width=0.1), colour = "#34a186")+
       geom_bar(aes(x = c(2020.2,2021.2,2022.2), y = HIV_Diagnoses_annualdata$infections, fill = "Infections from Cascade\nestimates 2023", colour = "Infections from Cascade\nestimates 2023"), stat="identity", width=0.4, alpha = 0.5)+
       geom_errorbar(aes(x = c(2020.2,2021.2,2022.2), ymin=HIV_Diagnoses_annualdata$infections_lower,ymax=HIV_Diagnoses_annualdata$infections_upper,width=0.1), colour = "#4cb1c4")+
       scale_colour_manual(name="",breaks = c("Infections", "Infections from Cascade\nestimates 2023"),labels = c("Infections", "Infections from Cascade\nestimates 2023"), values = c('#34a18680','#4cb1c480'))+
       scale_fill_manual(name="",breaks = c("Infections", "Infections from Cascade\nestimates 2023"),labels = c("Infections", "Infections from Cascade\nestimates 2023"), values = c('#34a18680','#4cb1c480'))+
       ylim(0,signif(max(newinfectionresults_peryear_95PI$diagnosis_upper),1)) +
       #scale_y_continuous(expand = c(0, 200), limits = c(0, NA))+
       scale_x_continuous(breaks = c(2020,2021,2022), 
                     labels = c("2020","2021","2022"))+ 
       xlab("Year") + ylab("Number") +
       theme_classic()+
       theme(plot.margin = margin(30, 0, 0, 30))+
       labs(tag = "  \n B") +
       theme(plot.tag.position = c(-0.02, 0.7))
newinfections_peryear_fig

combined_figure<-plot_grid(diagnosis_peryear_fig, newinfections_peryear_fig, ncol=1, align="v")

if (!file.exists(file.path(figFolder, "newinfections_diagnosis_peryear_fig20240523.png"))) {
    SaveFigure(figFolder,"newinfections_diagnosis_peryear_fig20240523",combined_figure)
}
if (!file.exists(file.path(figFolder, "diagnosis_peryear_fig20240708.png"))) {
    SaveFigure(figFolder,"diagnosis_peryear_fig20240708",diagnosis_peryear_fig)
}
```

